name: AWS Beanstalk deploy

on:
  push:
    branches:
      - "nextjs"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}} 

      - name: Generate deployment package
        run: npm run next-install && npm run generate-zip

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET }}
          application_name: next-app
          environment_name: next-app-dev
          version_label: next-app-${{ steps.buildnumber.outputs.build_number }}
          region: ap-northeast-1
          deployment_package: deploy.zip
